version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mi_tienda
      - POSTGRES_USER=admin2808
      - POSTGRES_PASSWORD=jose2808
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image:  dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=josevalencia654@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5454:80